### ISSUE TITLE
Icloud.com 

### ISSUE THREAD

**Issue by Alexis81** [ronny3050/email-mirror#11]
Hello,

I use an Icloud account for my mail, and when launching email, I have an error:

Type: 'no'
TextCode: 'AUTHENTICATIONFIELD'
Source: 'authentication'

Here is my configuration of the module:

{
			module: 'email',
            		position: 'bottom_left',
            		header: 'Email',
            		config:{
                		user: 'alexisolivan@me.com',
                		password: 'xxxx',
                		host: 'imap.mail.me.com',
                		port: 993,
                		tls: true,
                		authTimeout: 10000,
                		numberOfEmails: 5,
                		fade: true
        		},
		}

**Comment by Alexis81** [comment]
Back trace :

Email notifier error:  { Error: Authentication failed
    at Connection._resTagged (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Connection.js:1502:11)
    at Parser.<anonymous> (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Connection.js:194:10)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser._resTagged (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Parser.js:175:10)
    at Parser._parse (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Parser.js:139:16)
    at Parser._tryread (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Parser.js:53:12)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
  type: 'no',
  textCode: 'AUTHENTICATIONFAILED',
  source: 'authentication' }

**Comment by ronny3050** [comment]
Please double check your host name.
