### ISSUE TITLE
cant recieve new email

### ISSUE THREAD

**Issue by pawpawsoswag** [ronny3050/email-mirror#16]
my prblem is it cant recieve any email or notif that theres an email :(

**Comment by ronny3050** [comment]
Can you post the logs from your mirror? There might be an issue with connecting to your email account.

**Comment by pawan-kojhani** [comment]
same error is it can't receive any email notification

**Comment by ronny3050** [comment]
Can you please post your logs? Thanks!

**Comment by lsaguiar** [comment]
Hi Ronny,

I'm getting the same error and my log is below, please let me know how to solve the issue.

My best regards.

Email notifier error:  { Error: Web login required: https://support.google.com/mail/answer/78754 (Failure)
    at Connection._resTagged (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Connection.js:1502:11)
    at Parser.<anonymous> (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Connection.js:194:10)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser._resTagged (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Parser.js:175:10)
    at Parser._parse (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Parser.js:139:16)
    at Parser._tryread (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Parser.js:53:12)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7) type: 'no', textCode: 'ALERT', source: 'authentication' }

**Comment by ronny3050** [comment]
You need to ‘set lower security for apps’ https://www.google.com/settings/security/lesssecureapps

**Comment by lsaguiar** [comment]
Hi Ronny,
I'm still getting error, below the logs:

Email notifier error:  { Error: Invalid credentials (Failure)
    at Connection._resTagged (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Connection.js:1502:11)
    at Parser.<anonymous> (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Connection.js:194:10)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser._resTagged (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Parser.js:175:10)
    at Parser._parse (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Parser.js:139:16)
    at Parser._tryread (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Parser.js:53:12)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
  type: 'no',
  textCode: 'AUTHENTICATIONFAILED',
  source: 'authentication' }
Email notifier error:  { Error: Web login required: https://support.google.com/mail/answer/78754 (Failure)
    at Connection._resTagged (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Connection.js:1502:11)
    at Parser.<anonymous> (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Connection.js:194:10)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser._resTagged (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Parser.js:175:10)
    at Parser._parse (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Parser.js:139:16)
    at Parser._tryread (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Parser.js:53:12)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7) type: 'no', textCode: 'ALERT', source: 'authentication' }

Looking forward your reply.

Many thanks,
Leandro

**Comment by ronny3050** [comment]
`Error: Invalid credentials (Failure)` means your email username or password is wrong.

**Comment by GxnfrAli** [comment]
No New Emmail.........why?
no nottifiy about new mail
