### ISSUE TITLE
Email notifier error: Error: 1945498896

### ISSUE THREAD

**Issue by mvlanga** [ronny3050/email-mirror#29]
Hey, I got this error and I dont know how to fix it, can any1 help me?  

```
  at Error (native)
    at Socket.ondata (_stream_wrap.js:58:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20) source: 'socket' }
Email notifier error:  { Error: 1945498896:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../../vendor/node/deps/openssl/openssl/ssl/s23_clnt.c:794:
```

My config looks like this:

```
		{
			module: 'email',
                	position: 'bottom_left',
                	header: 'Email',
                	config: {
                    	accounts: [
                        	{
                            	user: 'mail@gmx.de',
                            	password: 'password',
                            	host: 'mail.gmx.net',
                            	port: 587,
                            	tls: true
                        	},
				{
                            	user: 'mail@gmx.de',
                            	password: 'password',
                            	host: 'mail.gmx.net',
                            	port: 587,
                            	tls: true
				}
                    	],
                        authTimeout: 10000,
                    	fade: true,
                    	maxCharacters: 30,
			numberOfEmails: 2
                	}
		}
```

**Comment by mtrr** [comment]
587 is the wrong port.
