### ISSUE TITLE
none mails but there is new mails on mu mail box gmail!

### ISSUE THREAD

**Issue by petitemuse** [ronny3050/email-mirror#42]
hello 

I did install the module and I am having the problem that it tells me no new mails but I did check in the mail box of gmail and I have 2 new mails

Any idea (I am totally new in this!!)

Thank you

**Comment by petitemuse** [comment]
Hello again,

did some changes and now I am now having Loading.... I am waiting since lol 24h and still loading...


    module: 'email',
                position: 'bottom_left',
                header: 'Email',
                config: {
                    accounts:
                        {
                                user: 'xxxxxxx@gmail.com',
                                password: 'xxxxxxxxxx',
                                host: 'imap.gmail.com',
                                port: 993,
                                tls: true,
                                authTimeout: 10000,
                                MaxCharacters: 50,
                                numberOfEmails: 2,
                                }
                        }
                },

what shoul I do? I am totaly new in this!! just bought the raspberry a week ago!

thank you,

Nora

**Comment by ronny3050** [comment]
Please try this: https://support.google.com/accounts/answer/6010255?hl=en

**Comment by petitemuse** [comment]
Thank, you,

I have done this but still I am getting Loading...
what else could it be?

**Comment by betaWeb** [comment]
Hello there, I've the same problem here and the "Less secure app access" is active..
I've 8 times "NEW MAIL" on the log and ths error :
```
Email notifier error:  { Error: Timed out while authenticating with server
    at Timeout._onTimeout (/var/www/html/Lab/MagicMirror/modules/email/node_modules/imap/lib/Connection.js:139:17)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) source: 'timeout-auth' }
```
I try to connect on Gmail accont.
