### ISSUE TITLE
Running into following issue

### ISSUE THREAD

**Issue by Sultan91** [ronny3050/email-mirror#5]
`Email notifier error:  { Error: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
    at Socket.ondata (_stream_wrap.js:58:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18) code: 'SELF_SIGNED_CERT_IN_CHAIN', source: 'socket' }
`

**Comment by ronny3050** [comment]
Could you try rebooting the pi and trying again? Please let me know, thanks!

**Comment by Sultan91** [comment]
Yes, actually the problem with Gmail itself. We need to make 3rd party access enabled in Gemail settings. Thanks for respond!
