### ISSUE TITLE
Error while using this module.

### ISSUE THREAD

**Issue by gitwaytogit** [ronny3050/email-mirror#64]
ERROR]  If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[2020-08-15 16:01:21.458] [LOG]    Email notifier error:  Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:413:19)
    at clearBuffer (_stream_writable.js:543:7)
    at Socket.Writable.uncork (_stream_writable.js:321:7)
    at JSStreamSocket.doWrite (internal/js_stream_socket.js:162:17)
    at JSStream.onwrite (internal/js_stream_socket.js:20:57)
    at Socket.ondata (internal/js_stream_socket.js:64:22)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10) {
  source: 'socket'
}
[2020-08-15 16:01:21.462] [ERROR]  Whoops! There was an uncaught exception...
[2020-08-15 16:01:21.463] [ERROR]  Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1317:34)
    at TLSSocket.emit (events.js:200:13)
    at TLSSocket._finishInit (_tls_wrap.js:792:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:606:12)
    at Socket.ondata (internal/js_stream_socket.js:64:22)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)

**Comment by ccfbeltran** [comment]
same here!
